name: Build and push image to Dockerhub

on:
  push:
    tags:
      - 'v*'

jobs:
  build_docker_images:
    runs-on: [ubuntu-latest]
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Extract metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DH_REPO_NAME}}
          tags: |
            type=semver,pattern={{version}}

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          logout: true

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Trigger redeploy
        run: |
          curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
